kind: Namespace
apiVersion: v1
metadata:
  name: my-devops

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: ijenkins
  namespace: my-devops
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: ijenkins:02
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 50000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: my-jenkins
      volumes:
        - name: my-jenkins
          emptyDir: {}

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: isonarqube
  namespace: my-devops
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:7.9.1-community
          ports:
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: sonarqube-conf
              mountPath: /opt/sonarqube/conf
            - name: sonarqube-extensions
              mountPath: /opt/sonarqube/extensions
            - name: sonarqube-logs
              mountPath: /opt/sonarqube/logs
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
      volumes:
        - name: sonarqube-conf
          emptyDir: {}
        - name: sonarqube-extensions
          emptyDir:
        - name: sonarqube-logs
          emptyDir: {}
        - name: sonarqube-data
          emptyDir: {}
---
