version: "3.3"
services:
  ijenkins:
    build:
      context: ./ijenkins
      cache_from: 
       - jenkins/jenkins:lts
       - ijenkins:01
    image: ijenkins:02
    ports:
        - "8080:8080"
        - "50000:50000"
    networks:
      default:
        ipv4_address: 172.19.0.10
    
    volumes:
        - type: volume
          source: my_jenkins
          target: /var/jenkins_home
  isonarqube:
    image: sonarqube:7.9.1-community
    ports:
        - "9005:9000"
    networks:
      default:
        ipv4_address: 172.19.0.11
    
networks:
  default:
    external:
      name: mynet
volumes:
    my_jenkins: