version: "3.3"
services:
  inginx:
    build:
      context: ./inginx
      cache_from: 
       - nginx:latest
    image: inginx:01
    expose:
      - "80"
    ports:
      - "80:80"
    networks:
      default:
        ipv4_address: 172.19.0.1
    depends_on:
        - phpinfo
  phpinfo:
    build: 
      context: ./phpinfo
      cache_from: 
       - php:5.6-fpm
    image: phpinfo:01
    expose:
      - "9000"
    ports:
      - "9000:9000"
    networks:
      default:
        ipv4_address: 172.19.0.3
networks:
  default:
    external:
      name: mynet